//
// Created by spl211 on 11/19/22.
//

#ifndef THECOALITIONRACE_MANDATESJOINPOLICY_H
#define THECOALITIONRACE_MANDATESJOINPOLICY_H


class MandatesJoinPolicy {

};


#endif //THECOALITIONRACE_MANDATESJOINPOLICY_H
